### 라이더 회원가입
POST localhost:8080/api/riders/new
Content-Type: application/json

{
  "name" : "없을무",
  "phone": "010-1234-5678"
}

### 라이더 로그인
POST localhost:8080/api/riders/login
Content-Type: application/json

{
  "phone": "010-1234-5678"
}

### 라이더 상태변경
PATCH localhost:8080/api/riders/status
Content-Type: application/json

{
  "status" : "OFFLINE"
}

### 대기중인 라이더 조회
GET localhost:8080/api/riders/available
Content-Type: application/json