### 가게 생성
POST localhost:8080/api/stores/new
Content-Type: application/json

{
  "ownerId" : 2,
  "storeName" : "라멘다이스키보이즈",
  "storeType" : "JAPANESE_FOOD"
}

### 타입별 가게 조회
GET localhost:8080/api/stores/type/JAPANESE_FOOD
Content-Type: application/json

### 전체 가게 조회
GET localhost:8080/api/stores/all
Content-Type: application/json

### 가게 이름으로 가게 조회
GET localhost:8080/api/stores/search?name=라멘다이스키보이즈
Content-Type: application/json